version: "3.8"

services:
  backend:
    image: timverbakel/myweightpal-backend:latest
    ports:
      - "5001:8080"
    networks:
      - mynetwork
    restart: always

  frontend:
    image: timverbakel/myweightpal-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60
    networks:
      - mynetwork

networks:
  mynetwork:
