version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_URL: http://localhost:5001
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
