// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.DoelGewichtModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("datumBehaald")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("datumToegevoegd")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("doelgewicht")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("DoelGewichtModel");
                });

            modelBuilder.Entity("DAL.Models.GewichtModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("datumToegevoegd")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("gewicht")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("GewichtModel");
                });
#pragma warning restore 612, 618
        }
    }
}
